apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: plex
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: plex
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: plex
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: Etc/UTC
            - name: VERSION
              value: docker
          image: lscr.io/linuxserver/plex:latest
          name: plex
          resources: {}
          volumeMounts:
            - mountPath: /downloads/complete
              name: plex-claim0
            - mountPath: /downloads
              name: plex-claim1
            - mountPath: /config
              name: plex-claim2
            - mountPath: /tv
              name: plex-claim3
            - mountPath: /movies
              name: plex-claim4
      restartPolicy: Always
      volumes:
        - name: plex-claim0
          persistentVolumeClaim:
            claimName: plex-claim0
        - name: plex-claim1
          persistentVolumeClaim:
            claimName: plex-claim1
        - name: plex-claim2
          persistentVolumeClaim:
            claimName: plex-claim2
        - name: plex-claim3
          persistentVolumeClaim:
            claimName: plex-claim3
        - name: plex-claim4
          persistentVolumeClaim:
            claimName: plex-claim4
status: {}
