apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: transmission
  name: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: transmission
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: transmission
    spec:
      containers:
        - env:
            - name: PGID
              value: "1000"
            - name: PUID
              value: "1000"
            - name: TZ
              value: America/Argentina/Buenos_Aires
          image: lscr.io/linuxserver/transmission:latest
          name: transmission
          ports:
            - containerPort: 9091
            - containerPort: 51413
            - containerPort: 51413
              protocol: UDP
          resources: {}
          volumeMounts:
            - mountPath: /config
              name: transmission-claim0
            - mountPath: /downloads/complete
              name: transmission-claim1
            - mountPath: /downloads
              name: transmission-claim2
            - mountPath: /watch
              name: transmission-claim3
      restartPolicy: Always
      volumes:
        - name: transmission-claim0
          persistentVolumeClaim:
            claimName: transmission-claim0
        - name: transmission-claim1
          persistentVolumeClaim:
            claimName: transmission-claim1
        - name: transmission-claim2
          persistentVolumeClaim:
            claimName: transmission-claim2
        - name: transmission-claim3
          persistentVolumeClaim:
            claimName: transmission-claim3
status: {}
